# Generated by Django 4.0.3 on 2022-06-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_book_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.JSONField(blank=True, null=True, verbose_name='タグ'),
        ),
    ]
