# Generated by Django 4.0.3 on 2022-04-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0003_editor_sex'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='editors',
            field=models.ManyToManyField(blank=True, to='editors.editor', verbose_name='編集者名'),
        ),
    ]
