# Generated by Django 4.0.3 on 2022-04-07 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenForRESTAPI',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('expired_date', models.DateTimeField(blank=True, null=True, verbose_name='有効期限')),
                ('expiration', models.CharField(choices=[('7 days', '1 週間'), ('30 days', '1 ヶ月間'), ('90 days', '3 ヶ月間'), ('no expiration', '有効期限なし')], max_length=16, null=True, verbose_name='設定有効期限')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'abstract': False,
            },
        ),
    ]
