# Generated by Django 4.0.3 on 2022-03-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='名前'),
        ),
    ]
