# Generated by Django 4.0.3 on 2022-03-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0002_alter_editor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], max_length=8, null=True, verbose_name='性別'),
        ),
    ]
